theme: jekyll-theme-minimal
title: [Valeria Ramírez Castañeda]
description: [Graduate Student at the Integrative Biology Department, UC Berkeley
M.Sc. Biology and science communication]
logo: ./logo.jpg
show_downloads: false
