theme: jekyll-theme-minimal
title: [Valeria Ramírez Castañeda]
description: [Colombian biologist interested in evolutionary biology, herpetology, science communication and inclusion/diversity/equity in STEM]
logo: [![VRC in Bojonawi Colombia](https://github.com/esperando370/vramirezc_website/commit/83f05dee85fe7578e5dc6ece782fffbff0cde8f1#diff-e85d34310d8bdab5944a28fad1bad192)]
