theme: jekyll-theme-minimal
title: Valeria Ramírez Castañeda
description: Colombian biologist interested in evolutionary biology, herpetology, science communication and inclusion/diversity/equity in STEM
logo: [Location of the logo]
